export const TRIGGER_UNIVERSE_KEY = 'trigger-event'
export const TRIGGER_GALAXY_KEY = 'trigger-event'
export const TRIGGER_STAR_KEY = 'trigger-event'
export const TRIGGER_REPORT_KEY = 'trigger-event'
export const TRIGGER_PLANET_KEY = 'trigger-event'
export const TRIGGER_CONSTELLATION_KEY = 'trigger-event'
export const TRIGGER_AUDIT_KEY = 'trigger-event'